CREATE FUNCTION [dbo].[AUTO_maCD]()
RETURNS CHAR(10)
AS
BEGIN
	DECLARE @ID CHAR(10)
	IF (SELECT COUNT(maCD) FROM [dbo].[CongDoan]) = 0
		BEGIN
			SET @ID = 'cd_0000000'
		END
	ELSE
		BEGIN
			SELECT @ID = MAX(RIGHT(maCD, 7)) FROM [CongDoan]
			SELECT @ID = CASE
				WHEN @ID >= 0 and @ID < 9 THEN 'cd_000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
				WHEN @ID >= 9 and @ID < 99 THEN 'cd_00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
				WHEN @ID >= 99 and @ID < 999 THEN 'cd_0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
				WHEN @ID >= 999 and @ID < 9999 THEN 'cd_000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
				WHEN @ID >= 9999 and @ID < 99999 THEN 'cd_00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
				WHEN @ID >= 99999 and @ID < 999999 THEN 'cd_0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
				WHEN @ID >= 999999 THEN 'cd_' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			END
		END
	RETURN @ID
END
GO